name: RPGItems
main: think.rpgitems.RPGItems
description: "RPGItems"
version: ${version}
depend: [LangUtils]
softdepend: [WorldGuard,NyaaUtils,Vault,Essentials]
authors: [Taiterio,cyilin,RecursiveG,Librazy]
website: "https://github.com/MrXiaoM/RPGItems-reloaded"
database: false
api-version: 1.13

commands:
  rpgitem:
    description: RPGItems' Admin Command Handler
    permission: rpgitem
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"
  rpgitems:
    description: RPGItems' User Command Handler
    permission: rpgitems
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  rpgitem.allowenchant.new:
    default: op
  rpgitem.allowenchant.old:
    default: op
  rpgitem.updateitem:
    default: op

  rpgitems.tomodel:
    default: false
  rpgitems.info:
    default: false