name: RPGItems
main: think.rpgitems.RPGItems
description: "RPGItems"
version: ${version}
softdepend: [WorldGuard,Vault,ItemsAdder,MythicMobs]
authors: [MrXiaoM,Taiterio,cyilin,RecursiveG,Librazy]
website: "https://github.com/MrXiaoM/RPGItems-reloaded"
database: false
api-version: 1.19
libraries:
  - 'com.udojava:EvalEx:2.7'
  - 'commons-lang:commons-lang:2.6'
  - 'net.bytebuddy:byte-buddy:LATEST'
  - 'org.jetbrains:annotations:24.0.1'

commands:
  rpgitem:
    description: RPGItems' Admin Command Handler
    permission: rpgitem
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"
  rpgitems:
    description: RPGItems' User Command Handler
    permission: rpgitems
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  rpgitem.allowenchant.new:
    default: op
  rpgitem.allowenchant.old:
    default: op
  rpgitem.updateitem:
    default: op

  rpgitems.tomodel:
    default: false
  rpgitems.info:
    default: false